export const profileConstants = {
    LOAD_PROFILES: "LOAD_PROFILES",
    SELECT_PROFILE: "SELECT_PROFILE",
    LOAD_CHART_DATA: "LOAD_CHART_DATA",
    SELECT_PROFILE_OTHER: "SELECT_PROFILE_OTHER",
    LOAD_CHART_DATA_OTHER: "LOAD_CHART_DATA_OTHER",
}
