# Generated by Django 3.1.3 on 2020-11-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='chart_object',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='person_object',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_object',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
