# Generated by Django 3.1.3 on 2020-11-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20201108_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_object',
        ),
        migrations.AddField(
            model_name='profile',
            name='latitude',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='longitude',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
