# Generated by Django 3.1.3 on 2021-01-03 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_auto_20210103_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birthstate',
            new_name='birthState',
        ),
    ]
