# Generated by Django 3.1.3 on 2020-11-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20201108_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_object',
            field=models.CharField(max_length=5000),
        ),
    ]
