export const profileConstants = {
    LOAD_PROFILES: "LOAD_PROFILES",
    ADD_PROFILE: "ADD_PROFILE",
    EDIT_PROFILE: "EDIT_PROFILE",
    SELECT_PROFILE: "SELECT_PROFILE",
    LOAD_CHART_DATA: "LOAD_CHART_DATA",
    SELECT_PROFILE_OTHER: "SELECT_PROFILE_OTHER",
    LOAD_CHART_DATA_OTHER: "LOAD_CHART_DATA_OTHER",
    ALLOW_SELECT_OTHER: "ALLOW_SELECT_OTHER",
    DISALLOW_SELECT_OTHER: "DISALLOW_SELECT_OTHER",
}
